class TorreBatallaDinamica
  # Estructura con todos los Entrenadores del juego
  ENTRENADORES_TORRE_BATALLA = [
    ["Javi", :Male, [:TAUROS, :PRIMARINA, :AMOONGUSS]],
    ["Gal", :Male, [:ORBEETLE, :POLTEAGEIST, :SNORLAX]],
    ["Albu", :Male, [:ZOROARK, :AMPHAROS, :VOLCARONA]],
    ["Javi", :Male, [:ELECTIVIRE, :KINGAMBIT, :LUDICOLO]],
    ["Jaime", :Male, [:SLAKING, :ANNIHILAPE, :ACCELGOR]],
    ["Sergio", :Male, [:MIMIKYU, :HERACROSS, :AMBIPOM]],
    ["Rogelio", :Male, [:CORVIKNIGHT, :ARCANINE, :LUDICOLO]],
    ["Sebax", :Male, [:HERACROSS, :DURANT, :KANGASKHAN]],
    ["Hellfire", :Male, [:FIDOUGH, :SALAMENCE, :NIDOKING]],
    ["Jorge", :Male, [:OCTILLERY, :JYNX, :ROSERADE]],
    ["Xander", :Male, [:SNORLAX, :DUBWOOL, :GASTRODON]],
    ["Pino", :Male, [:LOPUNNY, :DITTO, :VAPOREON]],
    ["Raulete", :Male, [:BLASTOISE, :GARDEVOIR, :FLYGON]],
    ["Carlitos", :Male, [:CROBAT, :FERROTHORN, :FLAREON]],
    ["Anju", :Male, [:ANNIHILAPE, :GENGAR, :DARMANITAN]],
    ["Maite", :Female, [:TOGEKISS, :AZUMARILL, :HATTERENE]],
    ["Ico", :Male, [:MILOTIC, :LEDIAN, :CORVIKNIGHT]],
    ["Polanquito", :Male, [:VENUSAUR, :CERULEDGE, :LUCARIO]],
    ["Raulito", :Male, [:GLISCOR, :CERULEDGE, :MILOTIC]],
    ["Lena", :Female, [:AERODACTYL, :EXCADRILL, :INFERNAPE]],
    ["Moe", :Male, [:CHANSEY, :GENGAR, :GRENINJA]],
    ["Jon", :Male, [:SWAMPERT, :PORYGONZ, :MAGNEZONE]],
    ["Varete", :Male, [:LOKIX, :SCEPTILE, :TINKATON]],
    ["Rogers", :Male, [:TOXTRICITY, :CHESNAUGHT, :APPLETUN]],
    ["Mimi", :Female, [:MAROWAK, :GRIMMSNARL, :PAWMOT]],
    ["Ferro", :Male, [:HARIYAMA, :MAGMORTAR, :GYARADOS]],
    ["Alon", :Male, [:GOLISOPOD, :GLIMMORA, :CHANDELURE]],
    ["Kamilo", :Male, [:TINKATON, :INTELEON, :SCRAFTY]],
    ["Juandi", :Male, [:SNORLAX, :LUCARIO, :GRENINJA]],
    ["Mati", :Male, [:RAICHU, :COPPERAJAH, :AEGISLASH]],
    ["Dani", :Male, [:GENGAR, :FLYGON, :SWAMPERT]],
    ["Furor", :Male, [:GHOLDENGO, :RAICHU, :MANTINE]],
    ["Aksnes", :Male, [:GLISCOR, :ROSERADE, :ELECTIVIRE]],
    ["Andrés", :Male, [:LYCANROC, :VIKAVOLT, :INFERNAPE]],
    ["Xavi", :Male, [:SERPERIOR, :COFAGRIGUS, :CORVIKNIGHT]],
    ["Mopli", :Male, [:MAMOSWINE, :GENGAR, :LUCARIO]],
    ["Arquilosofo", :Male, [:AMPHAROS, :UMBREON, :CROBAT]],
    ["Javi", :Male, [:ANNIHILAPE, :WEAVILE, :SCIZOR]],
    ["Raul", :Male, [:TOXICROAK, :REUNICLUS, :CENTISKORCH]],
    ["Abom", :Male, [:ABOMASNOW, :KILOWATTREL, :TENTACRUEL]],
    ["Domin", :Male, [:NIDOKING, :HONCHKROW, :MILOTIC]],
    ["Adrian", :Male, [:ANNIHILAPE, :RAICHU, :TOGEKISS]],
    ["Pacotazo", :Male, [:SNORLAX, :GRENINJA, :GALLADE]],
    ["Felipe", :Male, [:GYARADOS, :RILLABOOM, :ARCANINE]],
    ["Marco", :Male, [:WHIMSICOTT, :CLOYSTER, :BASTIODON]],
    ["Auron", :Male, [:CONKELDURR, :GENGAR, :ALAKAZAM]],
    ["Bjorn", :Male, [:ARCANINE, :STARAPTOR, :NIDOKING]],
    ["Dante", :Male, [:HOUNDOOM, :EMPOLEON, :DUSCLOPS]],
    ["Jano", :Male, [:GLALIE, :ROSERADE, :FLYGON]],
    ["Duby", :Male, [:AMBIPOM, :ZOROARK, :HELIOLISK]],
    ["Harvey", :Male, [:TYRANITAR, :ARMAROUGE, :SCRAFTY]],
    ["Renzo", :Male, [:AEGISLASH, :RAICHU, :WHISCASH]],
    ["Juanra", :Male, [:ARCHEOPS, :HAWLUCHA, :EMOLGA]],
    ["Exile", :Male, [:GARDEVOIR, :SYLVEON, :TINKATON]],
    ["Sam", :Male, [:ARCANINE, :APPLETUN, :CORVIKNIGHT]],
    ["Ander", :Male, [:GLISCOR, :FLAREON, :AMOONGUSS]],
    ["Andreb", :Male, [:GRANBULL, :DARMANITAN, :OCTILLERY]],
    ["Miguel", :Male, [:GENGAR, :AMOONGUSS, :MACHAMP]],
    ["Vicente", :Male, [:MUDSDALE, :ALAKAZAM, :ARCANINE]],
    ["Xareu", :Male, [:TOGEKISS, :JOLTEON, :EXCADRILL]],
    ["Alvaro", :Male, [:LANTURN, :HERACROSS, :DRAPION]],
    ["Javi", :Male, [:DELCATTY, :LIEPARD, :GOLURK]],
    ["Dixpler", :Male, [:VAPOREON, :LOPUNNY, :GARDEVOIR]],
    ["Gonzi", :Male, [:GASTRODON, :SCIZOR, :CROBAT]],
    ["Weigand", :Male, [:KILOWATTREL, :KLEAVOR, :STARAPTOR]],
    ["Chavmauel", :Male, [:SANDSLASH, :ZOROARK, :HERACROSS]],
    ["Madsur", :Male, [:GENGAR, :CHARIZARD, :UMBREON]],
    ["Alejandro", :Male, [:SCOLIPEDE, :GOLURK, :FERROTHORN]],
    ["Mael", :Male, [:SEVIPER, :RABSCA, :ESPATHRA]],
    ["Harold", :Male, [:TINKATON, :CONKELDURR, :LUDICOLO]],
    ["Ander", :Male, [:WEEZING, :CURSOLA, :DACHSBUN]],
    ["Sanchis", :Male, [:SWAMPERT, :VOLCARONA, :ELECTIVIRE]],
    ["Horowarang", :Male, [:SCIZOR, :ARAQUANID, :VOLCARONA]],
    ["Ywern", :Male, [:SIGILYPH, :SHUCKLE, :GASTRODON]],
    ["Soto", :Male, [:TOXAPEX, :GENGAR, :SIRFETCHD]],
    ["Darsh", :Male, [:EMPOLEON, :ALAKAZAM, :GENGAR]],
    ["Darsh", :Male, [:ESPEON, :ALAKAZAM, :EELEKTROSS]],
    ["Ro", :Male, [:HAXORUS, :SWAMPERT, :ARCANINE]],
    ["Matiusko", :Male, [:BRELOOM, :FLYGON, :CINDERACE]],
    ["Davebe", :Male, [:LAPRAS, :SNORLAX, :GENGAR]],
    ["Drake", :Male, [:KROOKODILE, :CHANDELURE, :GOLISOPOD]],
    ["Bernard", :Male, [:EXPLOUD, :SOLROCK, :HARIYAMA]],
    ["Guzman", :Male, [:INFERNAPE, :STARAPTOR, :BIBAREL]],
    ["Patz", :Male, [:LUXRAY, :FLYGON, :LAPRAS]],
    ["Roberto", :Male, [:DONDOZO, :VOLCARONA, :WEAVILE]],
    ["Carlos", :Male, [:CLOYSTER, :DRAPION, :MAGNEZONE]],
    ["Jordan", :Male, [:DUGTRIO, :BUTTERFREE, :HYPNO]],
    ["Marco", :Male, [:PALOSSAND, :SNORLAX, :DARMANITAN]],
    ["Kailian", :Male, [:TOGEKISS, :EXCADRILL, :HIPPOWDON]],
    ["Gonzalo", :Male, [:INFERNAPE, :TAUROS, :GALVANTULA]],
    ["Turi", :Male, [:ANNIHILAPE, :EMPOLEON, :GLISCOR]],
    ["Arya", :Female, [:GRENINJA, :CERULEDGE, :MIMIKYU]],
    ["Eusebio", :Male, [:SHUCKLE, :SLAKING, :STARMIE]],
    ["Janyon", :Male, [:GARDEVOIR, :SLAKING, :SWAMPERT]],
    ["Manu", :Male, [:WEAVILE, :CENTISKORCH, :GARGANACL]],
    ["Alberto", :Male, [:SWAMPERT, :SKELEDIRGE, :LUXRAY]],
    ["Slinky", :Male, [:JOLTEON, :GARGANACL, :ANNIHILAPE]],
    ["Tom", :Male, [:EXCADRILL, :KINGDRA, :LEAFEON]],
    ["Adrian", :Male, [:RAPIDASH, :CROBAT, :AGGRON]],
    ["Pablo", :Male, [:GRAFAIAI, :BAXCALIBUR, :QUAQUAVAL]],
    ["Carpinchoneitor", :Male, [:SCIZOR, :AGGRON, :SALAMENCE]],
    ["Lucas", :Male, [:GARDEVOIR, :ALTARIA, :MILOTIC]],
    ["Peludito", :Male, [:INFERNAPE, :GENGAR, :LUXRAY]],
    ["Miguel", :Male, [:LUCARIO, :GENGAR, :ARCANINE]],
    ["Levia", :Male, [:SLOWBRO, :RHYPERIOR, :GRIMMSNARL]],
    ["Alex", :Male, [:GASTRODON, :DARMANITAN, :SYLVEON]],
    ["Julio", :Male, [:BUTTERFREE, :HERACROSS, :GOLISOPOD]],
    ["Rosa", :Female, [:ESPEON, :SNORLAX, :GOODRA]],
    ["Dani", :Male, [:MEOWSCARADA, :MIMIKYU, :SNORLAX]],
    ["Davi", :Male, [:HERACROSS, :DONPHAN, :DARMANITAN]],
    ["Kuko", :Male, [:ABSOL, :KINGLER, :SCIZOR]],
    ["Manto", :Male, [:METAGROSS, :LAPRAS, :SYLVEON]],
    ["Paco", :Male, [:ANNIHILAPE, :CLAWITZER, :TOUCANNON]],
    ["Shuu", :Male, [:HIPPOWDON, :GASTRODON, :TYRANTRUM]],
    ["Chez", :Male, [:CROBAT, :WEEZING, :NIDOKING]],
    ["Zeltik", :Male, [:GENGAR, :EXCADRILL, :GIGALITH]],
    ["Victor", :Male, [:SCIZOR, :TOGEKISS, :ARCANINE]],
    ["Morlans", :Male, [:LYCANROC, :BUTTERFREE, :PYUKUMUKU]],
    ["Ramdon", :Male, [:TYPHLOSION, :GYARADOS, :NIDOKING]],
    ["Neru", :Male, [:ABSOL, :STARAPTOR, :FLYGON]],
    ["Josep", :Male, [:ABSOL, :STARAPTOR, :FLYGON]],
    ["Cosmen", :Male, [:NIDOKING, :TENTACRUEL, :MUK]],
    ["Ronda", :Female, [:CRADILY, :EXCADRILL, :WALREIN]],
    ["Alejandro", :Male, [:MAGNEZONE, :BLAZIKEN, :MILOTIC]],
    ["John", :Male, [:MISMAGIUS, :JOLTEON, :SWAMPERT]],
    ["Langtry", :Male, [:CROBAT, :MAGNEZONE, :KINGDRA]],
    ["Storm", :Male, [:EELEKTROSS, :GOLURK, :REUNICLUS]],
    ["Santiago", :Male, [:DARMANITAN, :LUXRAY, :OCTILLERY]],
    ["Marcos", :Male, [:TORTERRA, :GARCHOMP, :LUXRAY]],
    ["Mikel", :Male, [:TOXTRICITY, :FLYGON, :ANNIHILAPE]],
    ["Murutxu", :Male, [:TENTACRUEL, :AEGISLASH, :GLISCOR]],
    ["Cris", :Female, [:CHANDELURE, :ARMALDO, :GLALIE]],
    ["Masto", :Male, [:JELLICENT, :LAPRAS, :CHARIZARD]],
    ["Assaz", :Male, [:UMBREON, :MISMAGIUS, :CERULEDGE]],
    ["Sergio", :Male, [:TINKATON, :CHARIZARD, :LUDICOLO]],
    ["Scary", :Male, [:MISMAGIUS, :HONCHKROW, :CHANDELURE]],
    ["Gaviota", :Male, [:TROPIUS, :RELICANTH, :COFAGRIGUS]],
    ["Jose", :Male, [:BANETTE, :NINETALES, :CRUSTLE]],
    ["Korlat", :Male, [:LYCANROC, :CAMERUPT, :TAUROS]],
    ["Esteras", :Male, [:SCEPTILE, :MINIOR, :GALVANTULA]],
    ["Bastian", :Male, [:CERULEDGE, :LUDICOLO, :BRONZONG]],
    ["Xedator", :Male, [:GLISCOR, :JOLTEON, :EMPOLEON]],
    ["Epicuro", :Male, [:FLYGON, :VOLCARONA, :REUNICLUS]],
    ["Vrau", :Male, [:ROTOM, :RIBOMBEE, :DUBWOOL]],
    ["Edualfa", :Male, [:SCEPTILE, :SLOWKING, :ARCANINE]],
    ["Rodri", :Male, [:MIMIKYU, :SALAZZLE, :POLTEAGEIST]],
    ["Saakir", :Male, [:KINGLER, :SCIZOR, :BLASTOISE]],
    ["Alexander", :Male, [:ARMAROUGE, :MEOWSCARADA, :PAWMOT]],
    ["Eduardo", :Male, [:LANTURN, :PINSIR, :SKARMORY]],
    ["Aaron", :Male, [:VENUSAUR, :BRONZONG, :CROBAT]],
    ["Chema", :Male, [:DRAPION, :ALOMOMOLA, :FLORGES]],
    ["Abril", :Female, [:FARIGIRAF, :DEDENNE, :SWANNA]],
    ["Andryx", :Male, [:LICKILICKY, :MIMIKYU, :BLASTOISE]],
    ["Jere", :Male, [:SCEPTILE, :GLISCOR, :LUCARIO]],
    ["Chopita", :Male, [:AGGRON, :TREVENANT, :SWAMPERT]],
    ["Alex", :Male, [:ARCANINE, :STOUTLAND, :VOLCARONA]],
    ["Jaitor", :Male, [:LUCARIO, :CERULEDGE, :GOLISOPOD]],
    ["Amiama", :Male, [:NIDOQUEEN, :MIMIKYU, :AEGISLASH]],
    ["Victor", :Male, [:PRIMARINA, :AEGISLASH, :GARCHOMP]],
    ["Miriam", :Female, [:TENTACRUEL, :TINKATON, :CERULEDGE]],
    ["Miren", :Female, [:RAICHU, :HYDREIGON, :EMBOAR]],
    ["Eduardo", :Male, [:GIGALITH, :BLAZIKEN, :GLISCOR]],
    ["Juanito", :Male, [:GARDEVOIR, :UMBREON, :CHARIZARD]],
    ["Braan", :Male, [:AMBIPOM, :LUDICOLO, :MUK]],
    ["Noa", :Female, [:SLOWBRO, :CRUSTLE, :HAWLUCHA]],
    ["Angel", :Male, [:LUCARIO, :SHIFTRY, :CHARIZARD]],
    ["Aitor", :Male, [:SYLVEON, :ZOROARK, :VOLCARONA]],
    ["Coxer", :Male, [:SCYTHER, :SCIZOR, :KLEAVOR]],
    ["Sua", :Male, [:GLISCOR, :GASTRODON, :FERROTHORN]],
    ["Jose", :Male, [:SWAMPERT, :TINKATON, :ANNIHILAPE]],
    ["Alex", :Male, [:GRENINJA, :VENUSAUR, :ARMAROUGE]],
    ["Alain", :Male, [:ESPEON, :GLISCOR, :HYPNO]],
    ["Erico", :Male, [:AMPHAROS, :CLOYSTER, :VENUSAUR]],
    ["Samiel", :Male, [:GRANBULL, :FERROTHORN, :DUSKNOIR]],
    ["Dani", :Male, [:GENGAR, :TINKATON, :MAGMORTAR]],
    ["David", :Male, [:JELLICENT, :SCIZOR, :HYDREIGON]],
    ["Josemi", :Male, [:LUXRAY, :SHARPEDO, :MAWILE]],
    ["Lazaro", :Male, [:GALLADE, :ARCHALUDON, :KANGASKHAN]],
    ["Rawling", :Male, [:SCEPTILE, :EELEKTROSS, :CORVIKNIGHT]],
    ["Paulines", :Male, [:MACHAMP, :SWAMPERT, :TURTONATOR]],
    ["Quesada", :Male, [:PACHIRISU, :SNORLAX, :CORVIKNIGHT]],
    ["Lubu", :Male, [:PICHU, :PIKACHU, :RAICHU]],
    ["Helly", :Female, [:REVAVROOM, :TINKATON, :DACHSBUN]],
    ["Leeroy", :Male, [:MRRIME, :JYNX, :GOTHITELLE]],
    ["Gabriel", :Male, [:SLOWBRO, :UNFEZANT, :SCIZOR]],
    ["Wanted", :Male, [:MISMAGIUS, :TENTACRUEL, :LEAFEON]],
    ["Adolfito", :Male, [:AERODACTYL, :MUK, :DONPHAN]],
    ["Jorge", :Male, [:WOBBUFFET, :TOXAPEX, :FERROTHORN]],
    ["Neri", :Male, [:GENGAR, :INCINEROAR, :VENUSAUR]],
    ["Chaplin", :Male, [:MIGHTYENA, :SCEPTILE, :FLAREON]],
    ["Romeo", :Male, [:GOLEM, :WOBBUFFET, :SINISTCHA]],
    ["Miri", :Female, [:WHIMSICOTT, :PAWMOT, :GLACEON]],
    ["Kirsant", :Male, [:PELIPPER, :SEISMITOAD, :FERROTHORN]],
    ["Federico", :Male, [:LUCARIO, :CHARIZARD, :DARKRAI]],
    ["Serrano", :Male, [:SKUNTANK, :GOLURK, :FROSMOTH]],
    ["Pedro", :Male, [:ELECTIVIRE, :NIDOQUEEN, :MAMOSWINE]],
    ["Zumby", :Male, [:SPIRITOMB, :DRIFBLIM, :SLAKING]],
    ["Niko", :Male, [:MISMAGIUS, :TINKATON, :CLAWITZER]],
    ["Jaime", :Male, [:AEGISLASH, :BANETTE, :EXCADRILL]],
    ["Sunrise", :Male, [:LUCARIO, :ARCANINE, :MIMIKYU]],
    ["Hades", :Male, [:ARBOK, :INFERNAPE, :SCIZOR]],
    ["Pipol", :Male, [:DUSKNOIR, :JOLTEON, :ALAKAZAM]],
    ["Dodragon", :Male, [:SCEPTILE, :BLASTOISE, :TOXTRICITY]],
    ["David", :Male, [:PANGORO, :AEGISLASH, :GIGALITH]],
    ["Rodri", :Male, [:LUDICOLO, :MAGNEZONE, :RHYPERIOR]],
    ["Chus", :Male, [:BRELOOM, :SLAKING, :AZUMARILL]],
    ["Joaquin", :Male, [:CONKELDURR, :VIKAVOLT, :GIGALITH]],
    ["Arnaldo", :Male, [:ELECTRODE, :WEEZING, :ARMALDO]],
    ["Ivan", :Male, [:MAGMORTAR, :DRAGAPULT, :AERODACTYL]],
    ["Alejandro", :Male, [:CACTURNE, :NOIVERN, :RAMPARDOS]],
    ["Andres", :Male, [:SHUCKLE, :FROSLASS, :SCIZOR]],
    ["Mazoga", :Male, [:SNORLAX, :WHISCASH, :FORRETRESS]],
    ["Moyi", :Male, [:CHARIZARD, :HAXORUS, :KINGDRA]],
    ["Neon", :Male, [:DEWGONG, :SWAMPERT, :VOLCARONA]],
    ["Cris", :Female, [:JOLTEON, :AEGISLASH, :BLAZIKEN]],
    ["Tommy", :Male, [:SAMUROTT, :JOLTEON, :STARAPTOR]],
    ["Anjapelo", :Male, [:MACHAMP, :GENGAR, :MAGMORTAR]],
    ["Loosewin", :Male, [:LYCANROC, :PYUKUMUKU, :AURORUS]],
    ["Carlitos", :Male, [:TYPHLOSION, :GOURGEIST, :FLYGON]],
    ["Carlos", :Male, [:LUDICOLO, :CAMERUPT, :MANECTRIC]],
    ["Pedro", :Male, [:GLALIE, :PERRSERKER, :MAROWAK]],
    ["Ariel", :Female, [:MAGNEZONE, :DRAGONITE, :GARDEVOIR]],
    ["Josiko", :Male, [:GYARADOS, :MACHAMP, :ALAKAZAM]],
    ["Juanxo", :Male, [:ARCANINE, :VENUSAUR, :DECIDUEYE]],
    ["Roy", :Male, [:RAICHU, :CENTISKORCH, :GYARADOS]],
    ["Singa", :Male, [:GALLADE, :SCRAFTY, :MIENSHAO]],
    ["Ikkon", :Male, [:ESPEON, :GENGAR, :TOXAPEX]],
    ["Seara", :Male, [:SIRFETCHD, :URSALUNA, :RHYPERIOR]],
    ["Yarel", :Male, [:GLISCOR, :KINGDRA, :SNORLAX]],
    ["Serpo", :Male, [:SKELEDIRGE, :LUDICOLO, :TOXTRICITY]],
    ["Fiora", :Female, [:GARGANACL, :ANNIHILAPE, :KLEFKI]],
    ["Filali", :Male, [:CORVIKNIGHT, :SLAKING, :CLODSIRE]],
    ["Mendibil", :Male, [:FERROTHORN, :MUDSDALE, :TOXAPEX]],
    ["Espinola", :Male, [:MILOTIC, :DUSKNOIR, :BLAZIKEN]],
    ["Agebelda", :Male, [:ROTOM, :SWAMPERT, :TALONFLAME]],
    ["Alfredo", :Male, [:MAGMORTAR, :ELECTIVIRE, :DUSKNOIR]],
    ["Anitax", :Female, [:SYLVEON, :GARDEVOIR, :LAPRAS]],
    ["Kanh", :Male, [:LUXRAY, :BRELOOM, :SCIZOR]],
    ["Ijen", :Male, [:QUAGSIRE, :BELLOSSOM, :LAPRAS]],
    ["Enrique", :Male, [:FLOATZEL, :GOGOAT, :GALLADE]],
    ["Eustaquia", :Female, [:BLAZIKEN, :WIGGLYTUFF, :JOLTEON]],
    ["Sergi", :Male, [:KLEAVOR, :MILOTIC, :CHANDELURE]],
    ["Refos", :Male, [:TOGEKISS, :EXCADRILL, :SEAKING]],
    ["Kat", :Female, [:RILLABOOM, :FLORGES, :WHIMSICOTT]],
    ["Nailik", :Male, [:SNORLAX, :LUCARIO, :GRENINJA]],
    ["Gonzalo", :Male, [:COFAGRIGUS, :MIENSHAO, :KINGAMBIT]],
    ["Aitor", :Male, [:HERACROSS, :LUCARIO, :KINGDRA]],
    ["Alber", :Male, [:MISMAGIUS, :TALONFLAME, :GOLEM]],
    ["Alfombroma", :Male, [:EMPOLEON, :SABLEYE, :METAGROSS]],
    ["Kikegu", :Male, [:POLITOED, :FERALIGATR, :PORYGONZ]],
    ["Odracir", :Male, [:DUSKNOIR, :MILOTIC, :ELECTIVIRE]],
    ["Victor", :Male, [:TOGEKISS, :CARRACOSTA, :AMPHAROS]],
    ["Chanardo", :Male, [:CROBAT, :INTELEON, :TINKATON]],
    ["Kai", :Male, [:ESCAVALIER, :ZOROARK, :SCYTHER]],
    ["Aleix", :Male, [:ABSOL, :SCIZOR, :SEISMITOAD]],
    ["Alberto", :Male, [:ELECTIVIRE, :SPIRITOMB, :WHISCASH]],
    ["Antonio", :Male, [:GALVANTULA, :AMPHAROS, :LICKILICKY]],
    ["Facu", :Male, [:LUXRAY, :BLAZIKEN, :MAMOSWINE]],
    ["Atsel", :Male, [:DRAGALGE, :TOXAPEX, :SANDACONDA]],
    ["Erica", :Female, [:SUNFLORA, :TSAREENA, :VILEPLUME]],
    ["Aithor", :Male, [:DITTO, :AEGISLASH, :DRACOVISH]],
    ["Hevcyan", :Male, [:EXEGGUTOR, :HOUNDOOM, :ARAQUANID]],
    ["Icy", :Male, [:PELIPPER, :DURANT, :KINGDRA]],
    ["Octavio", :Male, [:KINGLER, :ELECTIVIRE, :MUK]],
    ["Muuu", :Male, [:DARMANITAN, :OMASTAR, :MAGNEZONE]],
    ["Borjomir", :Male, [:ARCANINE, :FERROTHORN, :SWALOT]],
    ["Santos", :Male, [:SUNFLORA, :ELECTRODE, :SKARMORY]],
    ["Splinter", :Male, [:RATICATE, :BLASTOISE, :TORTERRA]],
    ["Didi", :Female, [:FLYGON, :BUTTERFREE, :PAWMOT]],
    ["James", :Male, [:ESPEON, :LAPRAS, :AMPHAROS]],
    ["Umbotelon", :Male, [:SNORLAX, :LUCARIO, :LUDICOLO]],
    ["Galopeta", :Male, [:RAPIDASH, :FLAREON, :HIPPOWDON]],
    ["Pablo", :Male, [:CHARIZARD, :ESPEON, :KLEAVOR]],
    ["Sakre", :Male, [:ESPEON, :SHIFTRY, :TALONFLAME]],
    ["Toni", :Male, [:RAICHU, :VAPOREON, :DELPHOX]],
    ["Zenk", :Male, [:ACCELGOR, :KINGDRA, :BUTTERFREE]],
    ["Neri", :Male, [:GENGAR, :INCINEROAR, :VENUSAUR]],
    ["Yelepo", :Male, [:UNFEZANT, :GLACEON, :GHOLDENGO]],
    ["Altriz", :Male, [:DONPHAN, :SCEPTILE, :MILOTIC]],
    ["Nic", :Male, [:CAMERUPT, :APPLETUN, :PERRSERKER]],
    ["Salvador", :Male, [:FROSLASS, :BLAZIKEN, :LYCANROC]],
    ["Rouses", :Male, [:GASTRODON, :MIMIKYU, :MIENSHAO]],
    ["Midig", :Male, [:TREVENANT, :EXCADRILL, :GOLISOPOD]],
    ["Sam", :Male, [:ARCANINE, :RAICHU, :SCEPTILE]],
    ["Diego", :Male, [:FERROTHORN, :VOLCARONA, :TENTACRUEL]],
    ["Boski", :Male, [:CHANDELURE, :EXCADRILL, :ARAQUANID]],
    ["Pukas", :Male, [:TORTERRA, :ARMAROUGE, :ARCHALUDON]],
    ["Matolo", :Male, [:ZOROARK, :MAWILE, :ESPEON]],
    ["Feric", :Male, [:MALAMAR, :GLISCOR, :FROSMOTH]],
    ["Salvo", :Male, [:NOIVERN, :CRAWDAUNT, :HERACROSS]],
    ["Tinto", :Male, [:KABUTOPS, :WEAVILE, :ESCAVALIER]],
    ["Camero", :Male, [:PROBOPASS, :HIPPOWDON, :EXCADRILL]],
    ["Kyure", :Male, [:CENTISKORCH, :HAXORUS, :KINGAMBIT]],
    ["Nestor", :Male, [:FERROTHORN, :BLAZIKEN, :ALAKAZAM]],
    ["Onsass", :Male, [:STARAPTOR, :DRAPION, :AGGRON]],
    ["Nico", :Male, [:LAPRAS, :TANGROWTH, :CHARIZARD]],
    ["Rad", :Male, [:GYARADOS, :GLISCOR, :BEEDRILL]],
    ["Churti", :Male, [:HERACROSS, :GENGAR, :TYPHLOSION]],
    ["Tate", :Male, [:APPLETUN, :CARRACOSTA, :GARDEVOIR]],
    ["Herloz", :Male, [:CHARIZARD, :LYCANROC, :SIRFETCHD]],
    ["Alferrad", :Male, [:ARCANINE, :CHANDELURE, :SYLVEON]],
    ["Joel", :Male, [:HITMONLEE, :ARCANINE, :GYARADOS]],
    ["Fernando", :Male, [:TALONFLAME, :JELLICENT, :GOGOAT]],
    ["Rulotrik", :Male, [:ANNIHILAPE, :HITMONCHAN, :GALLADE]],
    ["Braian", :Male, [:INCINEROAR, :FERROTHORN, :PALAFIN]],
    ["Magmor", :Male, [:EMPOLEON, :TOGEKISS, :SKELEDIRGE]],
    ["David", :Male, [:LUXRAY, :CHANDELURE, :CLODSIRE]],
    ["Rice", :Male, [:DARMANITAN, :OCTILLERY, :JYNX]],
    ["Inaki", :Male, [:GENGAR, :EXCADRILL, :EMBOAR]],
    ["Sheraron", :Male, [:HAWLUCHA, :DACHSBUN, :GLISCOR]],
    ["Jago", :Male, [:INCINEROAR, :STARAPTOR, :GIGALITH]],
    ["Mejillon", :Male, [:PYUKUMUKU, :PINCURCHIN, :WISHIWASHI]],
    ["Ivan", :Male, [:GARDEVOIR, :JOLTEON, :LOPUNNY]],
    ["Camilo", :Male, [:SINISTCHA, :URSALUNA, :CHARIZARD]],
    ["Ventura", :Male, [:LICKILICKY, :TINKATON, :SCIZOR]],
    ["Josias", :Male, [:VENUSAUR, :SWAMPERT, :TOGEKISS]],
    ["Felipe", :Male, [:CLEFABLE, :UMBREON, :RIBOMBEE]],
    ["Antonio", :Male, [:SCEPTILE, :BLASTOISE, :TOXTRICITY]],
    ["Abeloxo", :Male, [:AGGRON, :FROSLASS, :SNORLAX]],
    ["Sepe", :Male, [:HERACROSS, :RHYPERIOR, :AMPHAROS]],
    ["Lali", :Female, [:WALREIN, :CAMERUPT, :DARMANITAN]],
    ["Kuro", :Male, [:ELECTRODE, :DEWGONG, :EXPLOUD]],
    ["Cuervo", :Male, [:NIDOKING, :HERACROSS, :LEAVANNY]],
    ["Esteban", :Male, [:BLASTOISE, :ELECTIVIRE, :MAGMORTAR]],
    ["Hanzo", :Male, [:PERSIAN, :KLEFKI, :EMBOAR]],
    ["Ryze", :Male, [:GLISCOR, :EMPOLEON, :ESPEON]],
    ["Zerod", :Male, [:SWAMPERT, :URSALUNA, :TALONFLAME]],
    ["Pregal", :Male, [:DONPHAN, :DELCATTY, :DARMANITAN]],
    ["David", :Male, [:PANGORO, :AEGISLASH, :GIGALITH]],
    ["Lucas", :Male, [:CHESNAUGHT, :KILOWATTREL, :KROOKODILE]],
    ["Ricacha", :Male, [:PORYGONZ, :BLASTOISE, :KABUTOPS]],
    ["Ruben", :Male, [:NINETALES, :SCEPTILE, :TOXICROAK]],
    ["Rokh", :Male, [:FLYGON, :HERACROSS, :CROBAT]],
    ["Abel", :Male, [:ESPEON, :MAMOSWINE, :TREVENANT]],
    ["Flancit", :Male, [:LUXRAY, :MAGNEZONE, :AMPHAROS]],
    ["Jesus", :Male, [:ROSERADE, :FERALIGATR, :NOIVERN]],
    ["Alexa", :Female, [:NINETALES, :UMBREON, :DACHSBUN]],
    ["Jade", :Female, [:MUDSDALE, :CHANDELURE, :ARAQUANID]],
    ["Areshiga", :Male, [:PALOSSAND, :NIDOKING, :GOLURK]],
    ["Singerwolves", :Male, [:BAXCALIBUR, :TOXTRICITY, :MAROWAK]],
    ["Cacharro", :Male, [:FERALIGATR, :WOBBUFFET, :ALAKAZAM]],
    ["Charcutero", :Male, [:TYRANITAR, :MILOTIC, :VENUSAUR]],
    ["Supra", :Male, [:GHOLDENGO, :CHANDELURE, :QUAQUAVAL]],
    ["Nicotanga", :Male, [:GYARADOS, :GOLURK, :MILOTIC]],
    ["Arthur", :Male, [:AEGISLASH, :GRIMMSNARL, :DRACOVISH]],
    ["Roto", :Male, [:KROOKODILE, :DRAPION, :VIKAVOLT]],
    ["Davilillo", :Male, [:ALAKAZAM, :LAPRAS, :EXEGGUTOR]],
    ["Capase", :Male, [:STEELIX, :ZANGOOSE, :ARMALDO]],
    ["Clara", :Female, [:CRAWDAUNT, :SCOLIPEDE, :PALOSSAND]],
    ["David", :Male, [:DUDUNSPARCE, :STEELIX, :MIMIKYU]],
    ["Iago", :Male, [:LEAFEON, :FROSLASS, :TYPHLOSION]],
    ["Marc", :Male, [:KINGAMBIT, :SCIZOR, :GHOLDENGO]],
    ["Kreithor", :Male, [:GLIMMORA, :HIPPOWDON, :EXCADRILL]],
    ["Burdoforo", :Male, [:ROYALEON, :CEFIREON, :DACHSBUN]],
    ["Boa", :Male, [:LUXRAY, :CERULEDGE, :GOLISOPOD]],
    ["Luis", :Male, [:PELIPPER, :KINGDRA, :DURANT]],
    ["Nacho", :Male, [:GASTRODON, :CERULEDGE, :SCRAFTY]],
    ["Hydeckar", :Male, [:GALLADE, :ESPEON, :SCYTHER]],
    ["Mathias", :Male, [:GYARADOS, :ALAKAZAM, :SYLVEON]],
    ["Mesto", :Male, [:MIMIKYU, :NINETALES, :ROTOM]],
    ["Nait", :Male, [:ARCANINE, :ALAKAZAM, :URSARING]],
    ["Umi", :Female, [:SCREAMTAIL, :LILLIGANT, :FROSLASS]],
    ["Didri", :Male, [:VIKAVOLT, :TALONFLAME, :BASTIODON]],
    ["Kuma", :Male, [:QUAGSIRE, :CLODSIRE, :STOUTLAND]],
    ["Elend", :Male, [:VOLCARONA, :GALLADE, :MAGNEZONE]],
    ["Mari", :Female, [:STARMIE, :WISHIWASHI, :MUDSDALE]],
    ["Poison", :Male, [:TOXAPEX, :CURSOLA, :GENGAR]],
    ["Mara", :Female, [:FLORGES, :PRIMARINA, :FURFROU]],
    ["Gabriel", :Male, [:GENGAR, :SWAMPERT, :BRELOOM]],
    ["Fernando", :Male, [:SCEPTILE, :CONKELDURR, :EXCADRILL]],
    ["Nandu", :Male, [:MAMOSWINE, :ROSERADE, :HELIOLISK]],
    ["Casimiro", :Male, [:DUDUNSPARCE, :TORKOAL, :MUSHARNA]],
    ["Jorge", :Male, [:STEELIX, :MILOTIC, :VOLCARONA]],
    ["Ralip", :Female, [:FERALIGATR, :ESPEON, :MEOWSCARADA]],
    ["Pilar", :Female, [:PELIPPER, :ARCHALUDON, :GLISCOR]],
    ["Somepano", :Male, [:PYUKUMUKU, :SNORLAX, :INFERNAPE]],
    ["Yugen", :Male, [:HELIOLISK, :CHANDELURE, :ALTARIA]],
    ["Javier", :Male, [:STARAPTOR, :EXCADRILL, :LANTURN]],
    ["Adriar", :Male, [:FROSLASS, :FALINKS, :GOLISOPOD]],
    ["Iñigo", :Male, [:DARMANITAN, :GOODRA_1, :MIMIKYU]],
    ["SSamurai", :Male, [:LUCARIO, :BLAZIKEN, :SCEPTILE]],
    ["Ina", :Male, [:KINGDRA, :DUSKNOIR, :GARDEVOIR]],
    ["Luis", :Male, [:EISCUE, :CLAYDOL, :SHIINOTIC]],
    ["Cabra", :Male, [:ANNIHILAPE, :SCRAFTY, :GOGOAT]],
    ["Wollem", :Male, [:WEEZING, :TYRANITAR, :EXCADRILL]],
    ["Lrj", :Male, [:ARMALDO, :SCOLIPEDE, :GOLISOPOD]],
    ["Sóspita", :Male, [:BLAZIKEN, :NINJASK, :CLODSIRE]],
    ["Amandine", :Female, [:VAPOREON, :DUGTRIO, :RIBOMBEE]],
    ["Lara", :Female, [:ZOROARK, :DITTO, :RIBOMBEE]],
    ["Stallord", :Male, [:SHARPEDO, :DECIDUEYE, :ARMAROUGE]],
    ["Jelen", :Female, [:WHISCASH, :CROBAT, :GARCHOMP]],
    ["Gustavo", :Male, [:BLAZIKEN, :LUDICOLO, :SIRFETCHD]],
    ["Ken", :Male, [:MAROWAK, :TYPHLOSION, :BLASTOISE]],
    ["Fubu", :Female, [:VENOMOTH, :STARMIE, :NINETALES]],
    ["Maca", :Female, [:AZUMARILL, :WEAVILE, :CERULEDGE], :CIENTIFICA],
    ["Miguel", :Male, [:MILOTIC, :SCIZOR, :HOUNDOOM]],
    ["Albert", :Male, [:MISMAGIUS, :EMBOAR, :GRUMPIG]],
    ["Kenzo", :Male, [:SKARMORY, :MILOTIC, :TOXAPEX]],
    ["Tomás", :Male, [:ANNIHILAPE, :AMOONGUSS, :CORVIKNIGHT]],
    ["Isaquiel", :Male, [:MACHAMP, :GASTRODON, :KROOKODILE]],
    ["Dorian", :Male, [:GOLURK, :MAGNEZONE, :VELUZA]],
    ["Nuri", :Female, [:CINCCINO, :DELPHOX, :LUXRAY]],
    ["Varo", :Male, [:SINISTCHA, :SKELEDIRGE, :GHOLDENGO]],
    ["Compy", :Male, [:NOIVERN, :TYRANITAR, :SKELEDIRGE]],
    ["Tóbal", :Male, [:SMEARGLE, :SNORLAX, :GHOLDENGO]],
    ["Batin", :Male, [:AGGRON, :SWALOT, :FLYGON]],
    ["Dani", :Male, [:KLEAVOR, :GOODRA_1, :CERULEDGE]],
    ["Junge", :Male, [:SHIINOTIC, :STARMIE, :LUXRAY]],
    ["Nieves", :Female, [:GARCHOMP, :BLISSEY, :HYDRAPPLE]],
    ["Blaze", :Male, [:TOXTRICITY, :TREVENANT, :BLAZIKEN]],
    ["Lobato", :Male, [:EMPOLEON, :SPIRITOMB, :STARAPTOR]],
    ["Ayoub", :Male, [:CROBAT, :NOIVERN, :STARMIE]],
    ["Nova", :Male, [:MIENSHAO, :HITMONCHAN, :BUZZWOLE]],
    ["Jinta", :Male, [:TOGEKISS, :ESPEON, :TYRANITAR]],
    ["Capi", :Male, [:CROBAT, :FERALIGATR, :CHARIZARD]],
    ["Benzema", :Male, [:BRELOOM, :TALONFLAME, :MILOTIC]],
    ["Madbeel", :Male, [:ZOROARK, :TOXAPEX, :MISMAGIUS]],
    ["Axel", :Male, [:GARDEVOIR, :LUCARIO, :STARAPTOR]],
    ["Lucy", :Female, [:KOMALA, :AURORUS, :DRAGALGE]],
    ["Diamond", :Male, [:CARBINK, :MALAMAR, :AEGISLASH]],
    ["Josema", :Male, [:KLEAVOR, :SYLVEON, :RAICHU]],
    ["Adrix", :Male, [:LUXRAY, :ABSOL, :ESPEON]],
    ["Pablito", :Male, [:GARGANACL, :MEOWSCARADA, :VOLCARONA]],
    ["Tatix", :Female, [:MEGANIUM, :PRIMARINA, :UMBREON]],
    ["Niso", :Male, [:RILLABOOM, :WOBBUFFET, :FALINKS]],
    ["Diamante", :Male, [:SNEASLER, :SCOLIPEDE, :BEEDRILL]],
    ["DualGemini", :Male, [:ZOROARK_1, :NINETALES_1, :STARAPTOR]],
    ["EBaru", :Male, [:TOGEKISS, :VENUSAUR, :DRAGONITE]],
  ]


  JEFES_TORRE_BATALLA = [
    ["Máximo", :Male, [:SKARMORY, :ARMALDO, :CLAYDOL, :CRADILY, :AGGRON, :METAGROSS], :MAXIMO],
    ["Cintia", :Female, [:SPIRITOMB, :MILOTIC, :LUCARIO, :ROSERADE, :TOGEKISS, :GARCHOMP], :CINTIA],
    ["Mirto", :Male, [:BOUFFALANT, :ESCAVALIER, :ACCELGOR, :SCOLIPEDE, :LEAVANNY, :VOLCARONA], :MIRTO],
    ["Kris", :Female, [:ESPEON, :MEGANIUM, :UMBREON, :TYPHLOSION, :TOGEKISS, :FERALIGATR], :TB1],
    ["Plata", :Male, [:WEAVILE, :GENGAR, :CROBAT, :ALAKAZAM, :MAGNEZONE, :FERALIGATR], :TB2],
    ["Eusine", :Male, [:HYPNO, :RAIKOU, :GENGAR, :ENTEI, :ELECTRODE, :SUICUNE], :TB3],
    ["Brendan", :Male, [:SWELLOW, :SCEPTILE, :CAMERUPT, :BLAZIKEN, :SHARPEDO, :SWAMPERT], :TB4],
    ["Blasco", :Male, [:ROSERADE, :TALONFLAME, :AZUMARILL, :MAGNEZONE, :GARCHOMP, :GALLADE], :TB5],
    ["Tristana", :Female, [:GOODRA, :TYRANTRUM, :NOIVERN, :ALTARIA, :EXPLOUD, :SALAMENCE], :TB6],
    ["Maya", :Female, [:STARAPTOR, :TORTERRA, :LUXRAY, :INFERNAPE, :LUCARIO, :EMPOLEON], :TB7],
    ["Israel", :Male, [:STARAPTOR, :FLOATZEL, :SNORLAX, :ROSERADE, :HERACROSS, :INFERNAPE], :TB8],
    ["Hilda", :Female, [:BRAVIARY, :SERPERIOR, :GALVANTULA, :EMBOAR, :HAXORUS, :SAMUROTT], :TB9],
    ["Cheren", :Male, [:LIEPARD, :SIMISEAR, :UNFEZANT, :GIGALITH, :HAXORUS, :SERPERIOR], :TB10],
    ["Bel", :Female, [:STOUTLAND, :SIMISAGE, :MUSHARNA, :MIENSHAO, :CHANDELURE, :EMBOAR], :TB11],
    ["N", :Male, [:ZOROARK, :VANILLUXE, :CARRACOSTA, :ARCHEOPS, :KLINKLANG, :RESHIRAM], :TB12],
    ["Mundánez", :Male, [:PERSIAN, :MEDICHAM, :FLYGON, :COPPERAJAH, :CARBINK, :LICKILICKY], :TB13],
    ["Serena", :Female, [:GOGOAT, :CHESNAUGHT, :LAPRAS, :DELPHOX, :LUCARIO, :GRENINJA], :TB14],
    ["Ciprés", :Male, [:PYROAR, :PANGORO, :HELIOLISK, :DRAGALGE, :CLAWITZER, :ZYGARDE], :TB15],
    ["Dianta", :Female, [:HAWLUCHA, :GOODRA, :AURORUS, :GOURGEIST, :TYRANTRUM, :GARDEVOIR], :TB16],
    ["Gala", :Female, [:LYCANROC, :MIENSHAO, :LAPRAS, :ROSERADE, :TURTONATOR, :XATU], :TB17],
    ["Kukui", :Male, [:DECIDUEYE, :MAGNEZONE, :INCINEROAR, :SNORLAX, :BRAVIARY, :PRIMARINA], :TB18],
    ["Guzmán", :Male, [:ARIADOS, :VIKAVOLT, :ARAQUANID, :RIBOMBEE, :BUZZWOLE, :GOLISOPOD], :TB19],
    ["Plumeria", :Female, [:TOUCANNON, :MUDSDALE, :MUK, :CROBAT, :KOMALA, :SALAZZLE], :TB20],
    ["Paul", :Male, [:DUBWOOL, :RILLABOOM, :CORVIKNIGHT, :CINDERACE, :SNORLAX, :INTELEON], :TB21],
    ["Sonia", :Female, [:GREEDENT, :ORBEETLE, :POLTEAGEIST, :GRIMMSNARL, :CENTISKORCH, :ARCHALUDON], :TB22],
    ["Lionel", :Male, [:AEGISLASH, :DRAGAPULT, :SEISMITOAD, :HAXORUS, :MRRIME, :CHARIZARD], :TB23],
    ["Mencía", :Female, [:ORTHWORM, :MEOWSCARADA, :PAWMOT, :SKELEDIRGE, :DUDUNSPARCE, :QUAQUAVAL], :TB24],
    ["Damián", :Male, [:MABOSSTIFF, :CLOYSTER, :SCOVILLAIN, :GARGANACL, :SHIINOTIC, :GREEDENT], :TB25],
    ["Noa", :Female, [:UMBREON, :VAPOREON, :LEAFEON, :JOLTEON, :FLAREON, :SYLVEON], :TB26],
    ["EricLostie", :Male, [:ALAKAZAM, :STEELIX, :SERPERIOR, :MILOTIC, :WIGGLYTUFF, :VOLCARONA], :TB27],
    ["Acromo", :Male, [:MAGNETON, :METAGROSS, :BEHEEYEM, :KLINKLANG, :MAGNEZONE, :ROTOM], :TB28],
    ["Guayo", :Male, [:VOLCARONA, :SALAMENCE, :FERROTHORN, :DRAGONITE, :FLAREON, :LATIOS], :TB29],
    ["Roxy", :Female, [:GRIMMSNARL, :TOXICROAK, :SCRAFTY, :LIEPARD, :DRAPION, :MORPEKO], :TB30],
    ["Mostaz", :Male, [:MIENSHAO, :KOMMOO, :CORVIKNIGHT, :LUXRAY, :LYCANROC, :URSHIFU], :TB31],
    ["e-Nigma", :Female, [:KILOWATTREL, :BELLIBOLT, :LUXRAY, :ELECTRODE, :ELECTIVIRE, :MISMAGIUS], :TB32],
    ["Ságita", :Female, [:ESPATHRA, :GOGOAT, :VELUZA, :AVALUGG, :KINGAMBIT, :GLIMMORA], :TB33],
    ["Cayena", :Male, [:WHISCASH, :CLODSIRE, :CAMERUPT, :DUGTRIO, :DONPHAN, :TINGLU], :TB34],
    ["Skyflyer", :Male, [:DECIDUEYE, :CORVIKNIGHT, :TYRANITAR, :WAILORD, :GALLADE, :STARAPTOR], :TB35],
    ["DPertierra", :Male, [:CLODSIRE, :CORVIKNIGHT, :MILOTIC, :SKELEDIRGE, :AMPHAROS, :SYLVEON], :TB36],
  ]


  FRASES_TORRE_BATALLA_GANAR = [
    "¡Me has ganado! ¡Felicidades!",
    "¡Pues sí que eres fuerte!",
    "¡Increíble! ¡Has demostrado ser un gran Entrenador!",
    "¡Tu estrategia ha sido perfecta!",
    "¡Vaya combate más emocionante! ¡Has ganado!",
    "¡Tus Pokémon y tú formáis un equipo imparable!",
    "¡He dado todo lo que tenía, pero tú has sido superior!",
    "¡Menuda batalla! ¡Te mereces esta victoria!",
    "¡Tu determinación ha marcado la diferencia!",
    "¡Jamás pensé que alguien pudiera vencerme así!",
    "¡Eres realmente excepcional como Entrenador!",
    "¡Tu vínculo con tus Pokémon es admirable!",
    "¡Has superado todas mis expectativas!",
    "¡Qué técnica tan impresionante! ¡Has ganado!",
    "¡Tu experiencia se nota! ¡Enhorabuena!",
    "¡Me has enseñado algo nuevo en este combate!",
    "¡Tu pasión por los Pokémon te ha llevado a la victoria!",
    "¡Definitivamente mereces estar en lo más alto!",
    "¡Has luchado con honor y has triunfado!",
    "¡Qué orgullo debe sentir tu equipo por ti!",
    "¡Tu talento natural es evidente! ¡Felicidades!",
    "¡Has convertido este combate en toda una lección!"
  ]

  FRASES_TORRE_BATALLA_PERDER = [
    "Creo que todavía te hace falta entrenar un poco.",
    "¡No te rindas! ¡Sigue entrenando y volverás más fuerte!",
    "¡Cada derrota es una lección! ¡Aprende de esto!",
    "¡Tu potencial es grande, solo necesitas más práctica!",
    "¡No pasa nada! ¡Los grandes Entrenadores también pierden!",
    "¡Vuelve cuando hayas fortalecido más a tu equipo!",
    "¡Tu determinación es admirable, pero necesitas más experiencia!",
    "¡Sigue así! ¡Estás en el buen camino!",
    "¡Un verdadero Entrenador nunca se da por vencido!",
    "¡Esta batalla te hará más sabio para la próxima!",
    "¡Tu espíritu es fuerte, solo falta pulir tu técnica!",
    "¡No te desanimes! ¡Todos empezamos desde abajo!",
    "¡Entrena más y regresa! ¡Te estaré esperando!",
    "¡Tus Pokémon confían en ti! ¡No los decepciones!",
    "¡La paciencia y el entrenamiento son la clave del éxito!",
    "¡Has luchado con valor, pero necesitas más preparación!",
    "¡El camino del Entrenador está lleno de desafíos!",
    "¡Fortalece el vínculo con tus Pokémon y vuelve!",
    "¡No hay atajos hacia la grandeza! ¡Sigue entrenando!",
    "¡Tu actitud es la correcta, solo necesitas más tiempo!",
    "¡Los derrotados de hoy son los campeones de mañana!",
    "¡Analiza esta batalla y aprende de tus errores!"
  ]


  # Arrays de tipos de entrenador según género
  TRAINER_TYPES_MALE = [
    :CAZABICHOS, :CAMPISTO, :CHICO, :CEREBRITO, :MONTANERO, :NADADOR, :CABALLERO, :MARINERO, 
    :MECANICO, :MOTORISTA, :ORNITOLOGO, :NINJA, :KARATEKA, :MEDIUM, :CIENTIFICO, :PESCADOR, 
    :LADRON, :VETERANO, :GUAY, :JUGON, :MALABARISTA, :MACARRA, :MATON, :TECNICO, :POKEMANIACO
    ]


  TRAINER_TYPES_FEMALE = [
    :CAZABICHAS, :CAMPISTA, :CHICA, :NADADORA, :FOTOGRAFA, :BRUJITA, :CABALLERA, :MECANICA, 
    :PESCADORA, :EXORCISTA, :DAMISELA, :NINJAA, :KARATEKAA, :CIENTIFICA, :VETERANA, :GUAYA,
    :MODELO, :JOVENRICA, :ESTUDIANTA
    ]

  VARNUM_TRAINER_TYPES = {
    # TRAINER_TYPES_MALE (1-19)
    :CAZABICHOS => 1, :CAMPISTO => 2, :CHICO => 3, :CEREBRITO => 4, :MONTANERO => 5,
    :NADADOR => 6, :CABALLERO => 7, :MARINERO => 8, :MECANICO => 9, :MOTORISTA => 10,
    :ORNITOLOGO => 11, :NINJA => 12, :KARATEKA => 13, :MEDIUM => 14, :CIENTIFICO => 15,
    :PESCADOR => 16, :LADRON => 17, :VETERANO => 18, :GUAY => 19, :JUGON => 20, :MALABARISTA => 21,
    :MACARRA => 22, :MATON => 23, :TECNICO => 24, :POKEMANIACO => 25,
    # TRAINER_TYPES_FEMALE (50-65)
    :CAZABICHAS => 50, :CAMPISTA => 51, :CHICA => 52, :NADADORA => 53, :FOTOGRAFA => 54,
    :BRUJITA => 55, :CABALLERA => 56, :MECANICA => 57, :PESCADORA => 58, :EXORCISTA => 59,
    :DAMISELA => 60, :NINJAA => 61, :KARATEKAA => 62, :CIENTIFICA => 63, :VETERANA => 64,
    :GUAYA => 65, :MODELO => 66, :JOVENRICA => 67, :ESTUDIANTA => 68,
    # JEFES ESPECIALES (100-138)
    :MAXIMO => 100, :CINTIA => 101, :MIRTO => 102, :TB1 => 103, :TB2 => 104, :TB3 => 105,
    :TB4 => 106, :TB5 => 107, :TB6 => 108, :TB7 => 109, :TB8 => 110, :TB9 => 111, 
    :TB10 => 112, :TB11 => 113, :TB12 => 114, :TB13 => 115, :TB14 => 116, :TB15 => 117, 
    :TB16 => 118, :TB17 => 119, :TB18 => 120, :TB19 => 121, :TB20 => 122, :TB21 => 123, 
    :TB22 => 124, :TB23 => 125, :TB24 => 126, :TB25 => 127, :TB26 => 128, :TB27 => 129, 
    :TB28 => 130, :TB29 => 131, :TB30 => 132, :TB31 => 133, :TB32 => 134, :TB33 => 135, 
    :TB34 => 136, :TB35 => 137, :TB36 => 138
  }
end
